#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

sed -i 's/\"network\"/\"modem\"/g' /usr/lib/lua/luci/controller/modem.lua

date_version=$(date +"%y.%m.%d")
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='V${date_version}'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt-V${date_version} '" >> /etc/openwrt_release

#echo "src/gz openwrt_core https://mirror.nju.edu.cn/immortalwrt/snapshots/targets/qualcommax/ipq807x/kmods/6.6.56-1-8ce1fcf08e9372905cb140eb5f56c2c0/" >> /etc/opkg/customfeeds.conf

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

ln -sf "/sbin/ip" "/usr/bin/ip"

sed -i '/core/d' /etc/opkg/distfeeds.conf
sed -i 's,downloads.immortalwrt.org,mirror.nju.edu.cn/immortalwrt,g' /etc/opkg/distfeeds.conf
sed -i 'check_signature/d' /etc/opkg.conf

exit 0
