#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

sed -i 's/mirrors.vsean.net/mirrors.jlu.edu.cn/g' /etc/opkg/distfeeds.conf
sed -i 's/openwrt/immortalwrt/g' /etc/opkg/distfeeds.conf
sed -i '/${interface:+-i/d' /etc/init.d/ttyd
sed -ri '/check_signature/s@^[^#]@#&@' /etc/opkg.conf

ln -sf "/sbin/ip" "/usr/bin/ip"

exit 0
