#!/bin/sh

uci set luci.main.lang=ru
uci commit luci

uci set fstab.@global[0].anon_mount=1
uci commit fstab

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i '703d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '703d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '703d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '703d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '703d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '703d' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i '/Powered by/,+3d' /usr/lib/lua/luci/view/themes/argon/footer.htm
sed -i '/Powered by/d' /usr/lib/lua/luci/view/themes/bootstrap/footer.htm

sed -i 's/192.168.1.1/192.168.8.1/g' /etc/wireless/mt7615/mt7615.1.5G.dat
sed -i 's/Openwrt_5G/WiFi6-5G/g' /etc/wireless/mt7615/mt7615.1.5G.dat
sed -i 's/CountryCode=US/CountryCode=CN/g' /etc/wireless/mt7615/mt7615.1.5G.dat

sed -i 's/192.168.1.1/192.168.8.1/g' /etc/wireless/mt7615/mt7615.1.2G.dat
sed -i 's/CR660X_2.4G/WiFi6-2.4G/g' /etc/wireless/mt7615/mt7615.1.2G.dat
sed -i 's/CountryCode=US/CountryCode=CN/g' /etc/wireless/mt7615/mt7615.1.2G.dat

sed -i 's/0x10/0/g' /etc/config/system
sed -i 's/switch0/0x10/g' /etc/config/system
sed -i 's/option dev/option port_mask/g' /etc/config/system
sed -i 's/netdev/switch0/g' /etc/config/system
sed -i 's/option mode/option default/g' /etc/config/system

ln -sf /sbin/ip /usr/bin/ip

sed -i "s/# //g" /etc/opkg/distfeeds.conf


sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache


exit 0
