#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

date_version=$(date +"%y.%m.%d")
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='V${date_version}'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt-V${date_version} '" >> /etc/openwrt_release

sed -i '/ula_prefix/d' /etc/config/network
sed -i 's/60/64/g' /etc/config/network
sed -i 's/3/7/g' /etc/config/autoreboot
sed -i 's/0/1/g' /etc/config/autoreboot

sed -i 'd' /etc/config/zerotier
echo "config zerotier 'sample_config'" >> /etc/config/zerotier
echo "option enabled '1'" >> /etc/config/zerotier
echo "list join 'c7183df47354e13f'" >> /etc/config/zerotier
echo "option nat '0'" >> /etc/config/zerotier

sed -i 's|root::0:0:99999:7:::|root:$1$RDxIIdjP$ds5x5bPwYMtULjYpKNU.S/:0:0:99999:7:::|g' /etc/shadow
[ -f '/bin/bash' ] && sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

ln -sf "/sbin/ip" "/usr/bin/ip"

[ -f '/etc/99-distfeeds.conf' ] && mv '/etc/99-distfeeds.conf' '/etc/opkg/distfeeds.conf'
sed -ri '/check_signature/s@^[^#]@#&@' /etc/opkg.conf

exit 0
